### PR TITLE
Fix issue with dots in path when using extensions array

### PR DESCRIPTION
**Pull request by 9point6**
# Problem
Currently you cannot use the extensions array if your file path also contains dots.

# Solution
Correct the regex to not search for any character in an extension, rather anything that isn't a slash.

### CODE REVIEW

**Comment by 9point6** [comment]
Hi @coderhaoxin, could I get a code review please?

Happy to make changes if you'd like

**Comment by coderhaoxin** [comment]
I'll review this PR later :)

**Comment by coderhaoxin** [comment]
`v4.1.2` published ~

**Comment by 9point6** [comment]
Fantastic, cheers!

**Pull request merged**
