### PR TITLE
use resolve-path

### LINKED ISSUE #9: extract sanitization
koa-send does a good job to analyze the path and sanitize it (decode, '..',, normalize).

this is something we probably want done even if there is a cache miss.

nevertheless, when there is a cache miss, we only get either an error or an empty path so we have to redo the same things.

what do you think would be the better way to handle this ? extract these parts in another middleware ? copy them ? how could this code be shared with koa-send without duplication (of code and of execution time) ?

### PR DESCRIPTION
**Pull request by coderhaoxin**
closes #9

### CODE REVIEW

**Comment by jonathanong** [comment]
any way to get the coverage up? :D

**Comment by coderhaoxin** [comment]
need move this logic to `resolve-path` ?

```js

/**
 * Check if `path` looks absolute.
 *
 * @param {String} path
 * @return {Boolean}
 * @api private
 */

function isAbsolute(path){
  if ('/' == path[0]) return true;
  if (':' == path[1] && '\\' == path[2]) return true;
  if ('\\\\' == path.substring(0, 2)) return true; // Microsoft Azure absolute path
}
```

**Comment by jonathanong** [comment]
were you able to remove that `isAbsolute()` function check without breaking tests? i think it's fine without it

**Comment by coderhaoxin** [comment]
> were you able to remove that isAbsolute() function check without breaking tests?

there are no tests for this

```js
if (':' == path[1] && '\\' == path[2]) return true;
if ('\\\\' == path.substring(0, 2)) return true; // Microsoft Azure absolute path
```

and the most broken change is send a absolute path.

**Comment by jonathanong** [comment]
31c6a5e7dd08ac80555f0f5a1cb7b3cd97ff527e

**Pull request closed without merging**
