### PR TITLE
add range support

### PR DESCRIPTION
**Pull request by lsy1458845893**
here is some test:
`curl http://localhost:3000/package.json -i -H "Range: bytes=0-50, 100-150"` 
 
```
HTTP/1.1 200 OK
Accept-Ranges: bytes
Last-Modified: Wed, 27 Mar 2019 11:20:08 GMT
Cache-Control: max-age=0
Content-Type: multipart/byteranges; boundary=--------------------------674091310343117359970110
Content-Length: 375
Date: Wed, 27 Mar 2019 11:45:17 GMT
Connection: keep-alive

--------------------------674091310343117359970110
Content-Type: .json
Content-Range: bytes 0-50/1149

{
  "name": "koa-send",
  "description": "Transfer
--------------------------674091310343117359970110
Content-Type: .json
Content-Range: bytes 100-150/1149

ersion": "5.0.0",
  "keywords": [
    "koa",
    "f
--------------------------674091310343117359970110--
```

### CODE REVIEW

**Comment by niftylettuce** [comment]
Can you please resolve conflicts and then ping me back?

**Comment by mreinstein** [comment]
Is this still wanted? I can submit a fresh PR with the conflicts resolved.

**Comment by mreinstein** [comment]
I guess the original author gave up on this PR. Is this something that koajs/send would accept? I'm happy to submit a new PR with the merge conflicts resolved if that's helpful. @3imed-jaberi @niftylettuce

**Comment by mreinstein** [comment]
Maybe it is better to just leave this alone, and point people to the `koa-range` middleware rather than baking this into `koa-send` ?

**Pull request closed without merging**
