### PR TITLE
Add generateIndex options

### PR DESCRIPTION
**Pull request by galkin**
@coderhaoxin, could you check this new functionality?

### CODE REVIEW

**Comment by galkin** [comment]
@coderhaoxin, @haoxin, could you check this pull request and provide your feedback?

**Comment by coderhaoxin** [comment]
What is the use case that we need generate index content dynamically ?

**Comment by galkin** [comment]
In my current project we use it for generating file list in the folder like [httpd](http://httpd.apache.org/docs/current/mod/mod_autoindex.html)

**Comment by galkin** [comment]
@coderhaoxin, do you need more information for decision?

**Comment by galkin** [comment]
@coderhaoxin, any updates?

**Comment by galkin** [comment]
@coderhaoxin, could you provide a feedback?

**Comment by galkin** [comment]
@coderhaoxin, could you provide a feedback?

**Comment by galkin** [comment]
@coderhaoxin, could you provide a feedback?

**Comment by galkin** [comment]
@coderhaoxin, could you provide a feedback?

**Comment by galkin** [comment]
@coderhaoxin, could you provide a feedback?

**Pull request closed without merging**
