### PR TITLE
config: add prefix pattern

### PR DESCRIPTION
**Pull request by xiongwilee**
add config opts.prefix

### CODE REVIEW

**Comment by coderhaoxin** [comment]
Unlike `koa-static` or `koa-static-cache`, when someone chooses `koa-send`,
there are more custom usage scenarios. Such as a lot of `path rewrite` scenarios.

**Comment by coderhaoxin** [comment]
@xiongwilee For your case, try https://github.com/koajs/rewrite ? :)

**Comment by xiongwilee** [comment]
用rewrite貌似不太合适啊，比如这样：

    // 配置静态文件路由
    vapp.use(koastatic(appPath + '/static', {
      prefix: 'static'
    }));

如果直接配置了prefix的话会方便很多，访问静态文件直接：

    http://localhost/static/* 就行

**Comment by coderhaoxin** [comment]
use `koa-mount`

```js
app.use(mount('/static', function *(){
  // ...
}))
```

**Comment by xiongwilee** [comment]
呃，好的，我试试

**Pull request closed without merging**
