### PR TITLE
Format option defaults to true #29

### PR DESCRIPTION
**Pull request by pierreburgy**
Format option defaults to true

### CODE REVIEW

**Comment by tj** [comment]
hmm, I don't remember a prop name being "format". Maybe we can change that as well if we're changing the api (need a major bump anyway)

**Comment by jonathanong** [comment]
@coderhaoxin can you shed some light on this?

**Comment by coderhaoxin** [comment]
will bump a major version later.

**Comment by coderhaoxin** [comment]
v3.0.0

**Pull request merged**
